version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.1

commands:
  build-docker:
    parameters:
      tag:
        type: string
    steps:
      - aws-cli/setup:
          profile-name: ecr-df
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run: |
          aws ecr get-login-password --region $AWS_DEFAULT_REGION --profile ecr-df | docker login --username AWS --password-stdin $ECR_ENDPOINT
          docker build -t vrai-server .
          docker tag vrai-server:latest ${ECR_ENDPOINT}/vrai-server:${TAG_VERSION}
          docker push ${ECR_ENDPOINT}/vrai-server:${TAG_VERSION}
jobs:
  deploy-development:
    executor: aws-cli/default
    steps:
      - build-docker:
          tag: development
      - run: |
          aws --profile=ecr-df ecs update-service --cluster vra-server-cluster-dev --service vrai-server-dev-service --force-new-deployment

  deploy-staging:
    executor: aws-cli/default
    steps:
      - build-docker:
          tag: staging
      - run: |
          aws --profile=ecr-df ecs update-service --cluster vra-server-cluster-dev --service vrai-server-staging --force-new-deployment

workflows:
  version: 2
  deploy:
    jobs:
      - deploy-development:
          filters:
            branches:
              only:
                - develop
      - manual-approval:
          type: approval
          requires:
            - deploy-development
      - deploy-staging:
          requires:
            - manual-approval
