FROM ghcr.io/windmill-labs/windmill:main

ARG WORKER_RAILWAY_TOKEN
ARG WORKER_VERCEL_TOKEN
ARG WORKER_DATOCMS_TOKEN
ARG WORKER_GITHUB_TOKEN
ARG WORKER_GITHUB_USERNAME
ARG WORKER_GITHUB_EMAIL
ARG WORKER_SHOPIFY_TOKEN
ARG WORKER_OPENAI_TOKEN

RUN apt update -y
RUN apt install npm -y

RUN npm i -g pnpm

RUN npm i -g @genql/cli

RUN npm i -g vercel

RUN npm i -g @railway/cli

RUN npm i -g @datocms/cli

RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://repo.charm.sh/apt/gpg.key | gpg --dearmor -o /etc/apt/keyrings/charm.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | tee /etc/apt/sources.list.d/charm.list
RUN apt update -y
RUN apt install mods -y

CMD ["windmill"]
