#!/usr/bin/env bash

set -euo pipefail

. prelude

GITEMAIL=$(git config user.email)

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

NODEPATH=$(which node)
NODEVERSION=$(node --version)

bootstrap() {
  if [ ! -f $LOG_FILE ]; then
    log_info "Creating log file $LOG_FILE"
  fi

  get_gum

  kv_hset "$GITEMAIL" \
    "node_path" "$NODEPATH" \
    "node_version" "$NODEVERSION" \
    "last_seen" "$TS" \
    "cli_version" "$CLI_VER" # tup=$(kv_hgetall "$GITEMAIL" | jq '.result')

  gum style --foreground 51 --border double --border-foreground 57 --padding "1 2" --margin "1 2" --align center "$GITEMAIL" \
    "CLI Version: $CLI_VER" \
    "Node: $NODEVERSION" \
    "Nodepath: $NODEPATH"
}

export -f bootstrap
