#!/usr/bin/env bash

set -euo pipefail

. prelude

GITEMAIL=$(git config user.email)

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

NODEPATH=$(which node)
NODEVERSION=$(node --version)
GUMVERSION=$(gum --version | awk '{print $3}')
DENOVERSION=$(deno --version | awk '{print $2}' | head -n1)

bootstrap() {
  if [ ! -f $LOG_FILE ]; then
    log_info "Creating log file $LOG_FILE"
  fi

  upgrade_gum

  kv_hset "$GITEMAIL" \
    "node_path" "$NODEPATH" \
    "node_version" "$NODEVERSION" \
    "last_seen" "$TS" \
    "cli_version" "$CLI_VER" \ # tup=$(kv_hgetall "$GITEMAIL" | jq '.result')
    "gum_version" "$GUMVERSION" \
    "deno_version" "$DENOVERSION"

  gum style --foreground 51 --border double --border-foreground 57 --padding "1 2" --margin "1 2" --align center "$GITEMAIL" \
    "CLI: $CLI_VER" \
    "Node: $NODEVERSION" \
    "Gum: $GUMVERSION" \
    "Deno" "$DENOVERSION"
}

export -f bootstrap
