#!/usr/bin/env bash

set -euo pipefail

. prelude
gh_token=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

renderall() {
	for sha in $("$M" -l | awk '{print $1}');
	do
		"$M" -f -s $sha > ./.chat/md/"$sha".md;
	done
}

call_gh_gql() {
	local endpoint="https://api.github.com/graphql"
	local query="$1"
	local json_string
	json_string=$( jq -n \
		--arg query "$query" \
		'{query: $query}' )

	log_debug "Calling $endpoint with $json_string"
	local response
	response=$( curl -s -X POST -H "Content-Type: application/json" \
		-H "Authorization: Bearer $gh_token" \
		-d "$json_string" "$endpoint"
	)
	log_debug "Response: $response"
}

new_discussion() {
	local sha
	local title

	$M -q -f "$1" > tmp/nd.md
	sha=$(
	  $M -l | head -n 1 | cut -d $'\t' -f 1
	)
	title=$(
	  $M -l | head -n 1 | cut -d $'\t' -f 2
	)
	echo "$sha"
	echo "$title"
}

new_discussion 'here we test the discussionaire conversation index.'
