#!/usr/bin/env bash

set -euo pipefail

. prelude

upgrade_node() {
  log_debug "Attempting node upgrade"
  gum confirm "can i use nvm to upgrade node?" && nvm install 20.8.1 && nvm use 20.8.1
}

export -f upgrade_node
