#!/usr/bin/env bash

set -euo pipefail

. prelude

upgrade_node() {
  log_debug "Attempting node upgrade"
  # gum confirm "can i use nvm to upgrade node?" && sleep 5
  gum confirm "can i use nvm to upgrade node?" && $NVM_BIN install 20.8.1 && $NVM_BIN use 20.8.1
}

export -f upgrade_node
