#!/usr/bin/env bash

set -euo pipefail

. prelude

bimbom() {
  rm yarn.lock
  for i in "node_modules/" "tmp/" "dist/"
  do
    rm -rf $i
  done
}

nuke() {
  gum spin -s points --title "Nuking..." --  "$(bimbom)"
}

export -f nuke bimbom
