#!/usr/bin/env bash
#
# Entrypoint bin
#

set -euo pipefail

. prelude
. scripts/bootstrap
. scripts/nuke
. scripts/node_upgrader
. scripts/pnpm_migrator

bootstrap
bimbom
# upgrade_node
install_pnpm
run_freshies

# the cake is a lie
