#!/usr/bin/env bash

set -euo pipefail

. prelude
. scripts/bootstrap
. scripts/node_upgrader
. scripts/pnpm_migrator
. scripts/nuke

main() {
  bootstrap
  nuke
  upgrade_node
  install_pnpm
}

main
