import {
  EARRING_PRODUCT_TYPE,
  NECKLACE_PRODUCT_TYPE,
  BRACELET_PRODUCT_TYPE,
  RING_PRODUCT_TYPE,
  ACCESSORY_PRODUCT_TYPE,
  RING_SIZER_PRODUCT_TYPE,
  GIFT_CARD_PRODUCT_TYPE,
  GWP_PRODUCT_TYPE,
  MODULAR_JEWELRY_PRODUCT_SLUGS,
} from '@diamantaire/shared/constants';

const JEWELRY_PRODUCT_TYPES = [
  EARRING_PRODUCT_TYPE,
  NECKLACE_PRODUCT_TYPE,
  BRACELET_PRODUCT_TYPE,
  RING_PRODUCT_TYPE,
  ACCESSORY_PRODUCT_TYPE,
  RING_SIZER_PRODUCT_TYPE,
  GIFT_CARD_PRODUCT_TYPE,
  GWP_PRODUCT_TYPE,
];

const getIsJewelryProduct = (productType) => JEWELRY_PRODUCT_TYPES.includes(productType);

export const getIsJewelryProductSlug = (slug) => MODULAR_JEWELRY_PRODUCT_SLUGS.includes(slug);

export default getIsJewelryProduct;
