name: Playwright E2E Tests for PR
on:
  pull_request:
    branches:
      - develop
jobs:
  test_setup:
    name: Test setup - Waiting for Vercel 
    runs-on: ubuntu-latest
    outputs:
      preview_url: ${{ steps.waitForVercelPreviewDeployment.outputs.url }}
    steps:
      - name: Wait for Vercel preview deployment to be ready
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 1000
          check_interval: 30
          environment: Preview – darkside-main
      - run: echo ${{steps.waitForVercelPreviewDeployment.outputs.url}}


  test_e2e:
    needs: test_setup
    name: Executing tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install --product
      - run: pnpm add @nx/playwright --ignore-scripts
      - run: npx playwright install --with-deps
      - name: Run tests
        run:  cd apps/darkside/main && npx playwright test npx playwright test e2e/tests/  --workers=2
        env:
          test_env: ${{ needs.test_setup.outputs.preview_url }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: apps/darkside/main/e2e/output/
          retention-days: 30
      
